catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import *


app_name = CatalogConfig.name


urlpatterns = [
    path('', IndexView.as_view()),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('products/', ProductListView.as_view(), name='products_list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_item'),
    path('blog/', BlogListView.as_view(), name='blog'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<blog_slug>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<blog_slug>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog/<blog_slug>/', BlogDetailView.as_view(), name='blog_detail'),

]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from pytils.translit import slugify
from datetime import date



NULLABLE = {'null': True, 'blank': True}


class Product(models.Model):
    product_name = models.CharField(max_length=200, verbose_name='Наименование')
    product_info = models.CharField(max_length=300, verbose_name='Описание')
    product_image = models.ImageField(upload_to='products/', verbose_name='Изображение', **NULLABLE)
    product_category = models.CharField(max_length=200, verbose_name='Категория')
    product_price = models.FloatField(max_length=20, verbose_name='Цена')
    product_create_date = models.DateField(verbose_name='Дата создания')
    product_last_upd_dt = models.DateField(verbose_name='Дата последнего изменения')

    def __str__(self):
        return f"{self.pk} - {self.product_name}"

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Category(models.Model):
    category_name = models.CharField(max_length=100, verbose_name='Наименование')
    category_info = models.CharField(max_length=300, verbose_name='Описание категории')

    # created_dt = models.DateField(verbose_name='Дата создания', **NULLABLE)

    def __str__(self):
        return f"{self.pk} - {self.category_name}"

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Contacts(models.Model):
    contact_name = models.CharField(max_length=100, verbose_name='Наименование')
    contact_number = models.CharField(max_length=17, verbose_name='Телефонный номер')

    def __str__(self):
        return f"{self.pk} - {self.contact_name}"

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class Blog(models.Model):
    blog_name = models.CharField(max_length=200, verbose_name='Заголовок', unique=True)
    blog_slug = models.CharField(max_length=100, verbose_name='Slug', unique=True, **NULLABLE)
    blog_content = models.TextField(verbose_name='Содержимое', **NULLABLE)
    blog_image = models.ImageField(upload_to='blog/', verbose_name='Превью (изображение)', **NULLABLE)
    blog_create_date = models.DateField(verbose_name='Дата создания', default=date.today)
    blog_publicate_flg = models.BooleanField(verbose_name='Признак публикации', default=True)
    blog_views_count = models.IntegerField(verbose_name='Количество просмотров', default=0)
    
    def __str__(self):
        return self.blog_name

    def save(self, *args, **kwargs):
        self.blog_slug = slugify(self.blog_name)[:100]
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.blog_publicate_flg = False
        self.save()

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from catalog.models import Product, Contacts, Blog
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

#CBV
class IndexView(TemplateView):
    template_name = 'catalog/index.html'

class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'
    extra_context = {
        'title': 'Контакты'
    }

class ProductListView(ListView):
    model = Product
    extra_context = {
        'title': 'Товары'
    }

class ProductDetailView(DetailView):
    model = Product

class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(blog_publicate_flg=True)

        return queryset

class BlogDetailView(DetailView):
    model = Blog

    def get_object(self):
        blog_slug = self.kwargs['blog_slug']
        obj = get_object_or_404(self.model, blog_slug=blog_slug)
        return obj

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = context_data['object']
        return  context_data

    def get(self, request, *args, **kwargs):
        """Увеличивает счетчик просмотров статьи"""
        self.object = self.get_object()

        self.object.blog_views_count +=1
        self.object.save()

        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

class BlogCreateView(CreateView):
    model = Blog
    fields = ('blog_name', 'blog_content', 'blog_image')
    success_url = reverse_lazy('catalog:blog')

class BlogUpdateView(UpdateView, BlogDetailView):
    model = Blog
    fields = ('blog_name', 'blog_content', 'blog_image')

    def get_success_url(self):
        blog = self.get_object()

        return reverse_lazy('catalog:blog_detail', kwargs={'blog_slug': blog.blog_slug})

class BlogDeleteView(DeleteView, BlogDetailView):
    model = Blog
    success_url = reverse_lazy('catalog:blog')



#FBV
# def index(request):
#     return render(request, 'catalog/index.html')


# def products(request):
#     products = Product.objects.all()
#     context = {
#         'products': products
#     }
#
#     return render(request, 'catalog/product_list.html', context)


# def product(request, pk):
#     product_item = Product.objects.get(pk=pk)
#     context = {
#         'object': product_item
#     }
#
#     return render(request, 'catalog/product_detail.html', context)

catalog/templates/catalog/base.html
{% load custom_tags %}
{% load custom_filters %}

<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/bootstrap.min.js"> </script>
    <meta charset="UTF-8">
    <title>{% block title %}Главная{% endblock %}</title>
</head>
<body>
    <header>
        {% include 'catalog/includes/inc_catalog_menu.html' %}
    </header>
    <main>

    </main>
    <footer>

    </footer>

      <div class="container objects">
        {% block content %}
        {% endblock %}
      </div>
    <p>© 2023 Магазин электроники</p>



</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
<!DOCTYPE html>

<html lang="en">
<head>

    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/bootstrap.min.js"> </script>
    <meta charset="UTF-8">
    <title>{% block title %}Карточка блога{% endblock %}</title>
</head>
<body>

    <form method="post">
        {% csrf_token %}
        Вы уверены что хотите удалить блог?
        <br><input type="submit" class="btn btn-success" value="Да!">
        <a class="btn btn-secondary" href="{% url 'catalog:blog' %}" role="button">Назад </a>
    </form>



</body>
</html>

catalog/templates/catalog/blog_detail.html
<!DOCTYPE html>

<html lang="en">
<head>

    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/bootstrap.min.js"> </script>
    <meta charset="UTF-8">
    <title>{% block title %}Карточка блога{% endblock %}</title>
</head>
<body>
    <h2>{{ title }} </h2>

    <p> {{ object.blog_content }} </p>
    {% if object.blog_image %}
        <br> <img class="rounded-circle" src="{{ object.blog_image.url }}" alt="Generic placeholder image" width="200" height="200">
    {% else %}
        <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="200" height="200">
    {% endif %}
    <br><br> <a class="btn btn-secondary" href="{% url 'catalog:blog' %}" role="button">Назад </a>

    <p> Просмотры: {{ object.blog_views_count }}</p>
</body>
</html>

catalog/templates/catalog/blog_form.html
<!DOCTYPE html>

<html lang="en">
<head>

    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/bootstrap.min.js"> </script>
    <meta charset="UTF-8">
    <title>{% block title %}Карточка блога{% endblock %}</title>
</head>
<body>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="{% if object %}Сохранить{% else %}Создать{% endif %}">
        <a class="btn btn-secondary" href="{% url 'catalog:blog' %}" role="button">Назад </a>
    </form>



</body>
</html>

catalog/templates/catalog/blog_list.html
<!DOCTYPE html>

{% extends 'catalog/base.html'%}
{% block title %}Блог{% endblock %}


{% block content %}
        <a class="btn btn-secondary" href="{% url 'catalog:blog_create' %}" role="button" style="width: 1150px;">Создать блог</a>

        <div class="row">
        {% for object in object_list %}
            <a href="{% url 'catalog:blog_detail' object.blog_slug %}"><h4>{{ object.blog_name }}</h4></a>

          <div class="col-100">
              {% if object.blog_image %}
                <img class="rounded-circle" src="{{ object.blog_image.url }}" alt="Generic placeholder image" width="200" height="200">

              {% else %}
              <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="200" height="200">
              {% endif %}
            <p> {{ object.blog_content }} </p>
            <p> Просмотры: {{ object.blog_views_count }}
                <a class="btn btn-secondary" href="{% url 'catalog:blog_update' object.blog_slug %}" role="button">Изменить </a>
                <a class="btn btn-secondary" href="{% url 'catalog:blog_delete' object.blog_slug %}" role="button">Удалить </a>
            </p>



          </div>
          {% endfor %}
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html'%}


<html lang="en">
<head>
    {% block title %}О нас{% endblock %}
</head>
<body>

{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
{% endblock %}
</body>
</html>

catalog/templates/catalog/includes/inc_catalog_menu.html
<h1 align="center" style="color:Green">Магазин электроники</h1>
<nav>
    <h4 align="left"> Меню </h4>
  <ul>
    <li><a href="/">Главная</a></li>
    <li><a href="/products/">Товары</a></li>
    <li><a href="/blog/">Блог</a></li>
    <li><a href="/contacts/">О нас</a></li>
  </ul>
</nav>

catalog/templates/catalog/index.html
{% extends 'catalog/base.html'%}

catalog/templates/catalog/product_detail.html
<!DOCTYPE html>

{% load custom_tags %}
{% load custom_filters %}

<html lang="en">
<head>

    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/bootstrap.min.js"> </script>
    <meta charset="UTF-8">
    <title>{% block title %}Главная{% endblock %}</title>
</head>
<body>
    <tr> {{ object.product_name }}</tr>
    <br> <img class="rounded-circle" src="{{ object.product_image.url }}" alt="Generic placeholder image" width="200" height="200">
    <br> <a class="btn btn-secondary" href="{% url 'catalog:products_list' %}" role="button">Назад </a>
</body>
</html>

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load custom_tags %}
{% load custom_filters %}

{% block title %}Товары{% endblock %}

{% block content %}
  <div class="row">
    {% for object in object_list %}
    <div class="col-12">
      <div class="row">
        <div class="col-12">
          {% if object.product_image %}
            <img class="rounded-circle" src="{{ object.product_image.url }}" alt="Generic placeholder image" width="200" height="200">
          {% else %}
            <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="200" height="200">
          {% endif %}
        </div>
        <div class="col-12">
          <h4>{{ object.product_name }}</h4>
          <p>Цена: {{ object.product_price }}</p>
          <p>Описание: {{ object.product_info|slice:"100" }}</p>
          <a class="btn btn-secondary" href="{% url 'catalog:product_item' object.pk %}" role="button">Подробнее &raquo;</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock %}